# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `fraud_detect`")
spark.sql("USE SCHEMA `default`")

# COMMAND ----------

raw = spark.read.table("banking_demo.bronze.transactions_raw")
print("transactions_raw columns:")
print(raw.columns)
print("mcc_merchant" in raw.columns)  # must be True

# check 2 — does it exist in the cleansed stage?
cleansed = spark.read.table("banking_demo.bronze.transactions_cleansed_stage")
print("\ntransactions_cleansed_stage columns:")
print(cleansed.columns)
print("mcc_merchant" in cleansed.columns)  

# COMMAND ----------

display(spark.sql("SELECT * FROM samples.wanderbricks.users"))
